Repository jupyter/nbclient, pull requests merged in 2023-04, with the labels that each got.

#281 Use local coverage
  .github/workflows/main.yml
  README.md
  codecov.yml
  pyproject.toml
Labels: maintenance

#283 avoid duplicate 'Exception: message' in CellExecutionError
  nbclient/exceptions.py
Labels: bug

#282 include stream output in CellExecutionError
  nbclient/client.py
  nbclient/exceptions.py
  nbclient/tests/files/Skip Exceptions with Cell Tags.ipynb
  nbclient/tests/test_client.py
Labels: enhancement
